import 'package:flutter/material.dart';
import 'add_todo.dart';
import 'todo_details.dart';
import 'todo_list.dart';
import 'todo_model.dart';
import 'todo_database.dart';

class TodoHomePage extends StatefulWidget {
  const TodoHomePage({super.key});

  @override
  State<TodoHomePage> createState() => _TodoHomePageState();
}

class _TodoHomePageState extends State<TodoHomePage> {
  List<Todo> _todos = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadTodosFromDb();
  }

  // Load todos from the database
  Future<void> _loadTodosFromDb() async {
    setState(() {
      _isLoading = true;
    });
    final todos = await TodoDatabase.instance.getTodos();
    setState(() {
      _todos = todos;
      _isLoading = false;
    });
  }

  // Add a new todo to the database
  Future<void> _addTodo(String title, String description) async {
    final todo = Todo(
      id: 0, // id will be auto-generated by the database
      title: title,
      description: description,
      createdAt: DateTime.now(),
    );
    await TodoDatabase.instance.insertTodo(todo);
    await _loadTodosFromDb(); // Refresh the list
  }

  // Remove a todo from the database
  Future<void> _removeTodo(int id) async {
    await TodoDatabase.instance.deleteTodo(id);
    await _loadTodosFromDb();
  }

  // Toggle a todo's done state and update in the database
  Future<void> _toggleTodo(int id) async {
    final todo = _todos.firstWhere((t) => t.id == id);
    todo.isDone = !todo.isDone;
    todo.doneAt = todo.isDone ? DateTime.now() : null;
    await TodoDatabase.instance.updateTodo(todo);
    await _loadTodosFromDb();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Simple Todo App')),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                TodoList(
                  todos: _todos,
                  onToggle: _toggleTodo,
                  onDelete: _removeTodo,
                  onTap: (todo) {
                    Navigator.push(
                      context,
                      MaterialPageRoute(
                        builder: (context) => TodoDetails(todo: todo),
                      ),
                    );
                  },
                ),
              ],
            ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showModalBottomSheet(
            context: context,
            isScrollControlled: true,
            shape: const RoundedRectangleBorder(
              borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
            ),
            builder: (context) => SingleChildScrollView(
              child: Padding(
                padding: EdgeInsets.only(
                  bottom: MediaQuery.of(context).viewInsets.bottom,
                ),
                child: ConstrainedBox(
                  constraints: BoxConstraints(
                    maxHeight: MediaQuery.of(context).size.height * 0.45,
                  ),
                  child: AddTodo(
                    onAdd: (title, desc) {
                      Navigator.of(context).pop();
                      _addTodo(title, desc);
                    },
                  ),
                ),
              ),
            ),
          );
        },
        backgroundColor: Colors.blueAccent,
        child: const Icon(Icons.add, size: 32),
      ),
    );
  }
}